### ISSUE TITLE
Projects have a limit of 1200 items - we should automatically clean up old issues

### ISSUE THREAD

**Issue by galargh** [pl-strflt/ipdx#49]
Project items can be bulk-archived or bulk-deleted so it's not a terrible UX to have to do it manually but at some point, we should automate archiving/deleting closed project items older than X.

@BigLep @SgtPooki Tagging you because I know you are more involved with managing GitHub Projects. Please ping me if this limit starts affecting you.

**Comment by SgtPooki** [comment]
@galargh I think a cleanup process is a great idea.

By archiving old issues, would they automatically be closed, or just removed from the project?  I think if we're reaching that limit, we should be closing the issues as well. Would we be closing oldest issues first? We could also remove items from a project that are completed/wontfix. 

The GUI issues I can imagine being impacted most by this are discussion-based issues left open because desired features/improvements we *want* to implement have not been prioritized over other work. I would like some way to find these in the future if we ever run out of work.

**Comment by galargh** [comment]
> By archiving old issues, would they automatically be closed, or just removed from the project?

That's just archiving in the context of a project. We can now set up auto archiving rules per project, https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/archiving-items-automatically

Ping me if you want me to enable it for your projects. Or you can do it yourself. It's in Project Settings > Workflows.
